name: yoga_session_app
description: A Flutter project for a modular guided yoga session app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Media & JSON handling
  audioplayers: ^6.0.0
  provider: ^6.0.0
  path_provider: ^2.0.15
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # ✅ Assets needed for the yoga session
  assets:
    - assets/poses.json
    - assets/images/
    - assets/audio/
